apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels: 
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 1
  template:
    metadata:
      labels:
        app: "goserver"
    spec:
      containers:
        - name: "goserver"
          image: andrejr971/hello-go:v5.4
          livenessProbe: # Health check for the container
            httpGet:
              path: /healthz # Path to check for health
              port: 8000 # Port to check
            periodSeconds: 5 # How often to perform the check
            failureThreshold: 3 # Number of failures before marking the container as unhealthy
            timeoutSeconds: 1 # How long to wait for a response before timing out
            successThreshold: 1 # Number of successes before marking the container as healthy again


          envFrom: # Load environment variables from a ConfigMap
            - configMapRef:
                name: "goserver-env"
            - secretRef:
                name: "goserver-secret"
          
          volumeMounts: # Mount the ConfigMap as a volume
            - name: config
              mountPath: /go/myfamily # Path where the ConfigMap will be mounted in the container
              readOnly: true # The volume is read-only
            
      volumes:
        - name: config
          configMap:
            name: configmap-family
            items:
              - key: members
                path: family.txt

          # env: # Environment variables for the container
          #   - name: "NAME"
          #     valueFrom: 
          #       configMapKeyRef:
          #         name: "goserver-env"
          #         key: "NAME"
                  
          #   - name: "AGE"
          #     valueFrom: 
          #       configMapKeyRef:
          #         name: "goserver-env"
          #         key: "AGE"
          