apiVersion: v1
kind: Service
metadata:
  name: goserver-service
spec:
  selector:
    app: goserver
  type: NodePort
  ports:
    - name: goserver-service
      port: 4000
      targetPort: 8000 
      protocol: TCP
      nodePort: 30001 # NodePort exposes the service on each node's IP at a static port (the NodePort).
      # The NodePort must be in the range 30000-32767.