apiVersion: v1
kind: Service
metadata:
  name: goserver-service # name of the service
spec:
  selector:
    app: goserver # label selector to match the pods
  type: ClusterIP
  ports:
    - name: goserver-service # name of the port
      port: 4000 # port exposed by the service
      targetPort: 8000 # port exposed by the container
      protocol: TCP
